# Lip Sync Battle Seeds
# Create Users
User.create(name: 'David', email: 'sam@sam.com', password: 'david')
User.create(name: 'Erin', email: 'erin@erin.com', password: 'erin')
User.create(name: 'Shannon', email: 'shannon@shannon.com', password: 'shannon')
User.create(name: 'Mike', email: 'mike@mike.com', password: 'mike')
User.create(name: 'Nathan', email: 'nathan@nathan.com', password: 'nathan')
User.create(name: 'Jenni', email: 'jenni@jenni.com', password: 'jenni')
User.create(name: 'Sam', email: 'sam@sam.com', password: 'sam')
# Create Videos
Video.create(url: '9_iKKL21rZo?start=1m&end=2m;', artist: 'Garth Brooks', title: 'The Thunder Rolls')
Video.create(url: '4l6lpmlwznw?start=1m&end=2m;', artist: 'The Killers', title: 'Somebody Told Me')
Video.create(url: 'Ev4pwFMaZQc?start=1m&end=2m;', artist: 'Queen', title: 'We Are The Champions')
Video.create(url: 'SAI_Nv3qWto?start=1m&end=2m;', artist: 'Aretha Franklin', title: 'R-E-S-P-E-C-T')
Video.create(url: 'k2h9HPZhqHE?start=1m&end=2m;', artist: 'Tom Petty', title: "I Won't Back Down")
Video.create(url: 'Ty1WU8Yfs9Q?start=1m&end=2m;', artist: 'Bette Midler', title: 'Boogie Woogie Bugle Boy')
Video.create(url: 'KAFvlknsT4U?start=1m&end=2m;', artist: 'Carrie Underwood', title: 'Before He Cheats')
Video.create(url: 'CxmxDFZYwh0?start=1m&end=2m;', artist: 'Tina Turner', title: 'Proud Mary')
Video.create(url: '_Vj092UgKwQ?start=1m&end=2m;', artist: 'Bee Gees', title: "Stayin' Alive")
Video.create(url: 'HAlz5TiKOCM?start=1m&end=2m;', artist: 'Meghan Trainor', title: "All About That Bass")
Video.create(url: 'B02LXuKWGTI?start=1m&end=2m;', artist: 'Michael Jackson', title: 'Billie Jean')
Video.create(url: '8bRuj9lOWAo?start=1m&end=2m;', artist: 'The Von Trapp Children', title: 'So Long, Farewell')
Video.create(url: 'XrCCsUm8od8?start=1m&end=2m;', artist: 'The Highwaymen', title: 'Highwayman')
Video.create(url: '1xs17f0MApA?start=1m&end=2m;', artist: 'The Righteous Brothers', title: "You've Lost That Loving Feeling")
Video.create(url: 'prN3bPmDqr4?start=1m&end=2m;', artist: 'Vanilla Ice', title: 'Ice Ice Baby')
Video.create(url: 'z5X5zh00rdg?start=1m&end=2m;', artist: 'MC Hammer', title: "U Can't Touch This")
Video.create(url: 'HBG3hBBiYLk?start=1m&end=2m;', artist: 'TLC', title: 'Waterfalls')
Video.create(url: 'iiWoF5tvLG4?start=1m&end=2m;', artist: '2-Pac', title: 'California Love')
Video.create(url: 'BzG4lj0FkHQ?start=1m&end=2m;', artist: 'Ace of Base', title: 'All That She Wants')
Video.create(url: 'wT0z5VDC_iI?start=1m&end=2m;', artist: 'Prince', title: 'Little Red Corvette')
Video.create(url: 'cMWWBigvbkY?start=1m&end=2m;', artist: 'Cyndi Lauper', title: 'Girls Just Want To Have Fun')
Video.create(url: 'JyolhkqH4rU?start=1m&end=2m;', artist: 'Will Smith', title: 'Fresh Prince of Bel-Air Theme')
Video.create(url: 'WjE4Vxe5-Ak?start=1m&end=2m;', artist: 'Sugar Hill Gang', title: "Rapper's Delight")
Video.create(url: 'Pbp6W4N1N9s?start=1m&end=2m;', artist: 'Whitney Houston', title: 'The Greatest Love Of All')
Video.create(url: '-2UNsHZjBXQ?start=1m&end=2m;', artist: 'Coolio', title: "Gansta's Paradise")
Video.create(url: '-T5xWkO56GI?start=1m&end=2m;', artist: 'Jackson 5', title: 'I Want You Back')
Video.create(url: 'p6Io6XBRRUs?start=1m&end=2m;', artist: 'Men Without Hats', title: 'Safety Dance')
Video.create(url: 'rYGLrJhhbqM?start=1m&end=2m;', artist: 'Chumbawamba', title: 'Tubthumping')
Video.create(url: '51ybp_YFo7I?start=1m&end=2m;', artist: 'Styx', title: 'Mr Roboto')
Video.create(url: 'qDLJ3pUZm9A?start=1m&end=2m;', artist: 'Toto', title: 'Africa')
Video.create(url: 'R-w8qfns9FU?start=1m&end=2m;', artist: 'a-ha', title: 'Take On Me')
Video.create(url: 'DrFZ6fXyia0?start=1m&end=2m;', artist: 'Taylor Swift', title: 'Shake It Off')
Video.create(url: 'YUEAjS3urfA?start=1m&end=2m;', artist: 'Sublime', title: 'What I Got')
Video.create(url: 'ZDZtbBZuqb0?start=1m&end=2m;', artist: 'Ozzy Osbourne', title: 'Crazy Train')
Video.create(url: 'QGe1z8G-rRk?start=1m&end=2m;', artist: 'Rick James', title: 'Super Freak')
Video.create(url: 'iBJwhZCS9z4?start=1m&end=2m;', artist: 'Nirvana', title: 'Smells Like Teen Spirit')
Video.create(url: 'RLgIkHvXwzE?start=1m&end=2m;', artist: 'Beach Boys', title: 'Kokomo')
Video.create(url: 'iG88R5SwQRw?start=1m&end=2m;', artist: 'The Crystals', title: 'And Then He Kissed Me')
Video.create(url: 'EorP1U2TVso?start=1m&end=2m;', artist: 'Jerry Lee Lewis', title: 'Great Balls of Fire')
Video.create(url: 'R5MWCnKeH2s?start=1m&end=2m;', artist: 'Gorillaz', title: 'Clint Eastwood')
Video.create(url: 'UHDi_FSsA3M?start=1m&end=2m;', artist: 'The Rembrandts', title: "I'll Be There For You")


# Create Battles
